# Generated by Django 3.0 on 2019-12-07 04:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('player', '0002_auto_20191206_2306'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_finished', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(default=None, null=True)),
                ('player_1', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='player_1', to='player.Player')),
                ('player_2', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='player_2', to='player.Player')),
                ('winner', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='winner', to='player.Player')),
            ],
        ),
    ]
