# Generated by Django 3.0 on 2019-12-07 05:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_auto_20191206_2306'),
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='WinCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('killer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='killer', to='game.Action')),
                ('victim', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='victim', to='game.Action')),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('action_1', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='action_1', to='game.Action')),
                ('action_2', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='action_2', to='game.Action')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='game.Game')),
                ('winner', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='round_winner', to='player.Player')),
            ],
        ),
    ]
